.TH "bomber-girl" "6" "" "" "Konaste Linux"

.SH "NAME"
\fBbombergirl\fP \- Play \fBBomber Girl\fP via \fBkonaste\fP(1)


.SH "SYNOPSIS"
konaste [ \fU\-\-flags\fP ] bombergirl \fBkonaste.bomber-girl://...\fP


.SH "DESCRIPTION"
\fBBomber Girl\fP (Japanese: ボンバーガール) is an arcade game ported to home PCs, and a direct spin-off to KONAMI's Bomberman. The gameplay consists of planting bombs to blow up obstacles, weaken target objectives, and even eliminate other players. While online matchmaking is available, it requires purchasing BOMBERGIRL tickets. However, offline missions will be available to play.
.PP
Thanks to \fBBomber Girl\fP utilizing the Unity engine, it does not require numerous tweaks (other than DXVK) to run under Wine, compared to the BEMANI games.
.PP
For a list of usable flags, see the \fBUSABLE FLAGS\fP section within \fBkonaste\fP(1).

.SH "GAME CONTROLS"
\fBWASD\fP         move character
.br
\fBLeft Arrow\fP   plant bomb
.br
\fBDown Arrow\fP   use special ability
.br
\fBRight Arrow\fP  use ultimate
.br
\fBReturn\fP       detonate objective
.br
\fB0123456789\fP   use preset voice line

.SH "AUTHORS"
While the Konaste Linux script was written by Mizzt, \fBBomber Girl\fP was developed by KONAMI Amusement.

.SH "SEE ALSO"
\fBkonaste\fP(1),
\fBwine\fP(1)
